import {validateModel,generate,analyse,replay} from './core.mjs';
import {SCENARIOS} from './scenarios.mjs';

const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function browserValidation(m){const v=validateModel(m);if(JSON.stringify(m).length>500000||m?.places?.length>64||m?.transitions?.length>32)v.errors.push('Browser limit: 500 kB, 64 places and 32 transitions; executions are capped at 32 events.');return {ok:!v.errors.length,errors:v.errors};}
const clone=v=>JSON.parse(JSON.stringify(v)), KEY='gimmer-causal-plan-lab-v1', VERSION='1.0.0';
let current=SCENARIOS[0],model=clone(current.model),allocation='fifo',search=null,result=null,trace=[],selectedEvent=null,tab='causal';
const transitionName=id=>model.transitions.find(t=>t.id===id)?.label||id;
const eventName=id=>result?.events?.find(e=>e.id===id)?.label||id;
const fmt=x=>!Number.isFinite(x)?'—':x!==0&&(Math.abs(x)<0.001||Math.abs(x)>=1e7)?x.toExponential(3):Number(x.toFixed(3)).toLocaleString();
function error(message=''){ $('error').hidden=!message;$('error').textContent=message; }
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:VERSION,scenario:current.id,model,allocation,trace,tab}));$('save-status').textContent='Saved in this browser · model, ancestry choice and selected execution';}catch{$('save-status').textContent='Browser storage unavailable. Export the result to keep it.';}}
function setupOptions(){ $('scenario').innerHTML=SCENARIOS.map(s=>`<option value="${esc(s.id)}">${esc(s.title)}</option>`).join(''); }
function updateControls(){
  $('scenario').value=current.id;$('allocation').value=allocation;$('scenario-description').textContent=current.description||model.description||'';
  $('model-json').value=JSON.stringify(model,null,2);
  const resource=model.places.find(p=>p.kind==='resource');$('capacity-field').hidden=current.id!=='shared-resource'||!resource;
  if(resource){$('capacity').value=resource.initial;$('capacity-output').value=resource.initial;}
  document.querySelectorAll('[data-case]').forEach(b=>b.classList.toggle('active',b.dataset.case===current.id));
}
function chooseScenario(id,scroll=false){current=SCENARIOS.find(s=>s.id===id)||SCENARIOS[0];model=clone(current.model);allocation='fifo';trace=[];selectedEvent=null;error();updateControls();run(current.trace);if(scroll)$('workbench').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
function run(preferred=trace){
  error();const validation=browserValidation(model);if(!validation.ok){error(validation.errors.join('\n'));return;}
  const previousStatus={text:$('search-status').textContent,kind:$('search-status').className};let committed=false;
  $('generate').disabled=true;$('search-status').textContent='Searching within the declared firing bounds…';
  try{
    const nextSearch=generate(model,{maxExecutions:1500,maxNodes:50000,allocation});
    if(nextSearch.errors?.length){error('The model could not be searched. '+nextSearch.errors.join(' '));return false;}
    const preferredReplay=Array.isArray(preferred)?replay(model,preferred,{allocation}):null;
    const firstGoal=r=>r?.ok&&r.goalReached&&!r.markings.slice(0,-1).some(m=>Object.entries(model.goal).every(([p,n])=>m[p]>=n));
    const nextTrace=firstGoal(preferredReplay)?[...preferred]:(nextSearch.executions[0]||[]);
    const available=nextSearch.executions.slice(0,1500);
    if(firstGoal(preferredReplay)&&!available.some(t=>JSON.stringify(t)===JSON.stringify(nextTrace)))available.unshift(nextTrace);
    const nextResult=available.length?analyse(model,nextTrace,{allocation}):null;
    if(nextResult&&!nextResult.ok){error('The plan could not be certified. '+nextResult.errors.join(' '));return false;}
    search=nextSearch;trace=nextTrace;result=nextResult;
    $('execution').innerHTML=available.length?available.map((t,i)=>`<option value="${i}">${i+1}. ${esc(t.length?t.map(transitionName).join(' → '):'Goal already satisfied · identity execution')}</option>`).join(''):'<option value="">No complete execution</option>';
    $('execution')._traces=available;$('execution').value=String(Math.max(0,available.findIndex(t=>JSON.stringify(t)===JSON.stringify(trace))));
    $('execution').disabled=!available.length;
    $('search-status').className='status'+(search.complete?'':' warn');
    $('search-status').textContent=search.complete?`${available.length.toLocaleString()} complete execution${available.length===1?'':'s'} · search exhausted within declared firing bounds.`:`${available.length.toLocaleString()} complete executions found · ${search.reason==='maxTraceLength'?'32-event boundary':'search limit'} reached. Further executions may exist.`;
    if(!available.length)$('search-status').textContent=search.complete?'No complete execution reaches this goal within the declared firing bounds.':'Search stopped at its limit without a complete execution. This does not establish impossibility.';
    selectedEvent=null;$('edge-inspector').textContent='Select an event to inspect the tokens behind it.';render();save();committed=true;return true;
  }catch(e){error('The model could not be analysed: '+e.message);}
  finally{$('generate').disabled=false;if(!committed){$('search-status').textContent=previousStatus.text;$('search-status').className=previousStatus.kind;}}
}
function selectTrace(t){const candidate=analyse(model,t,{allocation});if(!candidate.ok){error('Execution was not selected. Previous result retained. '+candidate.errors.join(' '));$('execution').value=String($('execution')._traces.findIndex(x=>JSON.stringify(x)===JSON.stringify(trace)));return;}error();trace=[...t];result=candidate;selectedEvent=null;render();save();}
function selectAllocation(next){const old=allocation;allocation=next;if(!run(trace)){allocation=old;updateControls();render();}else $('allocation').value=allocation;}
function render(){
  $('result-title').textContent=current.id==='custom'?(model.title||'Your process'):current.title;
  if(!result||!result.ok||!result.goalReached){
    $('verdict').textContent='No complete plan';$('verdict').className='badge error-badge';$('verdict-explanation').textContent='Only a goal-reaching execution becomes a plan. Inspect the inputs, outputs and goal in the model to find what is missing.';
    $('metrics').innerHTML='';$('graph').innerHTML='<div class="empty-state">No certified execution. A stopped prefix is not a completed project.</div>';$('gantt').innerHTML='';$('edge-inspector').textContent='Adjust the model or choose another experiment.';
    $('exact-tree').innerHTML='';$('tree-intro').innerHTML='<p>No WBS certificate exists without a complete execution.</p>';$('obstruction').hidden=true;$('staged-tree').innerHTML='';$('stage-difference').innerHTML='';$('certificate').textContent='No result certified.';$('order-table').innerHTML='';$('export').disabled=true;renderModel();setTab(tab,false);return;
  }
  $('export').disabled=false;$('verdict').textContent=result.exactTree?'Exact tree found':'Exact DAG · no exact tree';$('verdict').className='badge'+(result.exactTree?'':' warn');
  $('verdict-explanation').textContent=result.exactTree?'A tree in this restricted sequential/parallel grammar preserves exactly the event order of the selected token-flow witness. No dependencies are added or lost.':'The selected token-flow witness has a dependency pattern this restricted tree grammar cannot preserve. Its exact causal graph and valid schedule remain available.';
  const count=typeof result.linearExtensions==='number'?result.linearExtensions:result.linearExtensions?.count;
  const metrics=[[result.events.length,'event occurrences'],[fmt(result.makespan),'earliest finish'],[count==null?'bounded':count.toLocaleString(),'lawful event orders'],[result.stagedAdded.length,'rules added by stages']];
  $('metrics').innerHTML=metrics.map(([v,l])=>`<div class="metric"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('');
  renderGraph();renderGantt();renderTree();renderModel();setTab(tab,false);
}
function levels(){const depth=new Map(result.events.map(e=>[e.id,0]));for(let k=0;k<result.events.length;k++)for(const [a,b]of result.order)depth.set(b,Math.max(depth.get(b),depth.get(a)+1));return depth;}
function renderGraph(){
  if(!result)return;const depth=levels(),groups=[];for(const e of result.events)(groups[depth.get(e.id)]??=[]).push(e);
  const cols=groups.length,width=Math.max(650,cols*177+28),height=Math.max(210,...groups.map(g=>g.length*90+55)),pos=new Map();
  groups.forEach((g,i)=>g.forEach((e,j)=>pos.set(e.id,{x:24+i*(width-225)/Math.max(1,cols-1),y:(height-g.length*80)/2+j*80})));
  const edgeKeys=new Set(),edges=[];for(const e of result.edges){const key=JSON.stringify([e.from,e.to]);if(edgeKeys.has(key))continue;edgeKeys.add(key);const pair=result.edges.filter(z=>z.from===e.from&&z.to===e.to);edges.push({...e,kind:pair.some(z=>z.kind!=='resource')?'condition':'resource',places:pair.map(z=>z.place).join(', ')});}
  let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Causal dependency graph. Exact event relationships are also available in the table below."><defs>${[['condition','#146c58'],['resource','#467889'],['added','#b96b29']].map(([id,c])=>`<marker id="arrow-${id}" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="${c}"/></marker>`).join('')}</defs>`;
  const line=e=>{const a=pos.get(e.from),b=pos.get(e.to);if(!a||!b)return'';const x=a.x+138,y=a.y+24,bx=b.x,by=b.y+24;const c=e.kind==='resource'?'#467889':e.kind==='added'?'#b96b29':'#146c58';const route=a.x===b.x?`M${x},${y} C${x+48},${y} ${x+48},${by} ${b.x+138},${by}`:`M${x},${y} C${x+35},${y} ${bx-35},${by} ${bx},${by}`;return`<path d="${route}" fill="none" stroke="${c}" stroke-width="1.8" ${e.kind==='added'?'stroke-dasharray="5 4"':''} marker-end="url(#arrow-${e.kind})"><title>${esc(eventName(e.from)+' → '+eventName(e.to)+' · '+(e.places||'Added stage precedence'))}</title></path>`;};
  svg+=edges.map(line).join('');if($('show-added').checked)svg+=result.stagedAdded.map(([from,to])=>line({from,to,kind:'added'})).join('');
  svg+=result.events.map(e=>{const p=pos.get(e.id),words=e.label.split(' '),lines=[''];for(const w of words){if((lines.at(-1)+' '+w).length>22)lines.push(w);else lines[lines.length-1]+=(lines.at(-1)?' ':'')+w;}return`<g class="event-node${selectedEvent===e.id?' selected':''}" data-event="${esc(e.id)}" role="button" tabindex="0" aria-label="Inspect ${esc(e.label)}"><rect x="${p.x}" y="${p.y}" width="138" height="52" rx="6" fill="#fffefa" stroke="#acbfad"/><text x="${p.x+9}" y="${p.y+13}" font-size="8" fill="#62716b">${esc(e.id)}</text>${lines.slice(0,2).map((l,i)=>`<text x="${p.x+9}" y="${p.y+29+i*12}" font-size="10" fill="#17332f">${esc(l)}</text>`).join('')}<title>${esc(e.label)} · ${e.duration} time units</title></g>`;}).join('');svg+='</svg>';$('graph').innerHTML=svg;
  $('graph').querySelectorAll('[data-event]').forEach(el=>{const select=()=>{selectedEvent=el.dataset.event;inspectEvent(selectedEvent);renderGraph();};el.addEventListener('click',select);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}});});
}
function inspectEvent(id){const e=result.events.find(x=>x.id===id),incoming=result.edges.filter(x=>x.to===id),outgoing=result.edges.filter(x=>x.from===id);$('edge-inspector').innerHTML=`<strong>${esc(e.label)}</strong> · ${esc(e.id)}<br>${incoming.length?'Receives: '+incoming.map(x=>`${esc(x.place)} from ${esc(eventName(x.from))} (${esc(x.kind)})`).join('; '):'All consumed inputs are available in the initial marking.'}${outgoing.length?'<br>Supplies: '+outgoing.map(x=>`${esc(x.place)} to ${esc(eventName(x.to))}`).join('; '):'<br>No later event consumes its outputs in this witness.'}`;}
function renderGantt(){
  const rows=result.schedule, width=760,height=rows.length*37+45,labelWidth=190,end=result.makespan||1,scale=(width-labelWidth-30)/end;
  let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Earliest schedule for the chosen token-flow witness">`;
  for(let i=0;i<=5;i++){const t=end/5*i,x=labelWidth+t*scale;svg+=`<line x1="${x}" y1="20" x2="${x}" y2="${height-10}" stroke="#e0e6dc"/><text x="${x}" y="13" font-size="9" text-anchor="middle" fill="#62716b">${fmt(t)}</text>`;}
  rows.forEach((s,i)=>{const y=28+i*37;svg+=`<text x="10" y="${y+16}" font-size="10" fill="#17332f">${esc(eventName(s.id).slice(0,30))}</text><rect x="${labelWidth+s.start*scale}" y="${y}" width="${Math.max(2,(s.end-s.start)*scale)}" height="24" rx="3" fill="${i%2?'#77a08b':'#397b61'}"><title>${esc(eventName(s.id))}: ${s.start}–${s.end}</title></rect>`;});svg+='</svg>';$('gantt').innerHTML=svg;
  $('order-table').innerHTML=`<table><caption>Timing and all strict predecessors</caption><thead><tr><th>Event</th><th>Start</th><th>Finish</th><th>Must follow</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${esc(eventName(s.id))}<br><code>${esc(s.id)}</code></td><td>${fmt(s.start)}</td><td>${fmt(s.end)}</td><td>${result.order.filter(([a,b])=>b===s.id).map(([a])=>esc(eventName(a))).join(', ')||'Initial inputs'}</td></tr>`).join('')}</tbody></table>`;
}
function treeHTML(t){if(!t)return'';if(t.children?.length===0)return '<div class="tree-task">Identity · no event required</div>';if(t.type==='task')return`<div class="tree-task"><code>${esc(t.id)}</code>${esc(t.label||eventName(t.id))}</div>`;return`<div class="tree-node ${esc(t.type)}"><div class="tree-label">${t.type==='sequence'?'THEN · SEQUENCE':'TOGETHER · PARALLEL'}</div><div class="tree-children">${t.children.map(treeHTML).join('')}</div></div>`;}
function renderTree(){
  $('tree-intro').innerHTML=result.exactTree?'<h3>A faithful elementary WBS</h3><p class="help">“Then” orders every event across its blocks. “Together” introduces no order between blocks. Here that grammar exactly matches the selected causal witness.</p>':'<h3>Keep the crossing as a graph</h3><p class="help">No exact leaf/sequence/parallel tree exists for this selected witness. Forcing a tree requires changing its order. The causal plan remains the exact usable result.</p>';
  $('exact-tree').innerHTML=result.exactTree?treeHTML(result.tree):'<div class="empty-state">Exact dependency DAG retained<br><strong>No additional precedence imposed</strong></div>';
  $('obstruction').hidden=result.exactTree||!result.obstruction;
  if(result.obstruction){const o=result.obstruction;$('obstruction').innerHTML=`<h4>A four-event obstruction</h4><p>The induced order on these four events has the N pattern. Every other pair among them is incomparable.</p><p>${[o.a,o.b,o.c,o.d].filter(Boolean).map(id=>`<code>${esc(id)}</code> ${esc(eventName(id))}`).join('<br>')}</p><p>Required pairs: ${(o.relations||[]).map(([a,b])=>`${esc(a)} → ${esc(b)}`).join(' · ')}</p><p>A typed process diagram can keep these selective wires. Sequencing whole blocks cannot express them exactly.</p>`;}
  $('staged-tree').innerHTML=treeHTML(result.stagedTree);
  $('stage-difference').innerHTML=`<p><strong>${result.stagedAdded.length} added precedence relation${result.stagedAdded.length===1?'':'s'}.</strong> ${result.stagedAdded.length?'These are restrictions introduced by the display rule.':'For this witness, the stage rule adds no restriction.'}</p>${result.stagedAdded.length?'<p>'+result.stagedAdded.map(([a,b])=>`${esc(eventName(a))} → ${esc(eventName(b))}`).join('<br>')+'</p>':''}<p>Exact witness finish: <strong>${fmt(result.makespan)}</strong>. Forced-stage finish: <strong>${fmt(result.stagedMakespan)}</strong>.</p>${result.lostOrder?`<p>A lawful order the stage tree excludes:<br><code>${esc(result.lostOrder.join(' → '))}</code></p>`:''}`;
  const le=typeof result.linearExtensions==='number'?result.linearExtensions:result.linearExtensions?.count,te=typeof result.exactTreeExtensions==='number'?result.exactTreeExtensions:result.exactTreeExtensions?.count;
  $('certificate').innerHTML=`<ul><li>Goal reached by legal token consumption and production.</li><li>${result.events.length} distinct event occurrences; repeated firings keep separate IDs.</li><li>Chosen ancestry rule: ${allocation==='fifo'?'oldest':'newest'} available token first.</li><li>${result.exactTree?'Event identities and the full transitive order agree with the compiled tree.':'Exact tree compilation refused; the dependency graph preserves the full order.'}</li><li>Lawful linear orders: ${le==null?'enumeration limit reached':le}. ${result.exactTree?'Exact-tree orders: '+(te??'bounded')+'.':''}</li><li>Search ${search.complete?'exhausted':'truncated'} within explicit firing bounds; no claim about unbounded processes.</li></ul>`;
}
function markingValue(m){return m;}
function renderModel(){
  $('model-table').innerHTML=`<table><caption>Transitions, inputs, outputs and limits</caption><thead><tr><th>Work</th><th>Consumes</th><th>Produces</th><th>Duration</th><th>Max firings</th></tr></thead><tbody>${model.transitions.map(t=>`<tr><td>${esc(t.label)}<br><code>${esc(t.id)}</code></td><td>${Object.entries(t.inputs).map(([p,n])=>`${n} ${esc(p)}`).join('<br>')}</td><td>${Object.entries(t.outputs).map(([p,n])=>`${n} ${esc(p)}`).join('<br>')}</td><td>${t.duration}</td><td>${t.maxFirings}</td></tr>`).join('')}</tbody></table><p class="help">Goal: ${Object.entries(model.goal).map(([p,n])=>`${esc(p)} ≥ ${n}`).join(', ')}. Places: ${model.places.map(p=>`${esc(p.id)} (${esc(p.kind)}, initially ${p.initial})`).join('; ')}.</p>`;
  $('trace').textContent=trace.length?trace.map(transitionName).join(' → '):result?.goalReached?'Goal already satisfied · identity execution (no event required).':'No goal-reaching execution.';
  $('markings').innerHTML=result?`<table><caption>Collective marking after each sequential firing</caption><thead><tr><th>Step</th>${model.places.map(p=>`<th>${esc(p.id)}</th>`).join('')}</tr></thead><tbody>${result.markings.map((m,i)=>{const v=markingValue(m);return`<tr><td>${i===0?'Initial':esc(trace[i-1]||i)}</td>${model.places.map(p=>`<td>${esc(v[p.id]??0)}</td>`).join('')}</tr>`;}).join('')}</tbody></table>`:'';
  const pc=$('provenance-comparison');pc.hidden=current.id!=='token-provenance'||!result;
  if(!pc.hidden){const other=analyse(model,trace,{allocation:allocation==='fifo'?'lifo':'fifo'});const same=JSON.stringify(other.markings)===JSON.stringify(result.markings);const timingSame=JSON.stringify(other.schedule)===JSON.stringify(result.schedule);pc.innerHTML=`<h4>Hold the recorded project fixed. Change only ancestry.</h4><p>Collective marking trace: <strong>${same?'identical':'different'}</strong>. Earliest event timing: <strong>${timingSame?'identical':'different'}</strong>.</p><p>Selected witness: <strong>${result.exactTree?'exact Seq/Par tree':'no exact Seq/Par tree'}</strong>.<br>Other ancestry rule: <strong>${other.exactTree?'exact Seq/Par tree':'no exact Seq/Par tree'}</strong>.</p><p>The recorded token counts do not determine this certificate. It belongs to a selected token-flow witness.</p><button class="secondary" id="flip-ancestry">Switch ancestry and inspect the other result</button>`;$('flip-ancestry').onclick=()=>{selectAllocation(allocation==='fifo'?'lifo':'fifo');};}
}
function setTab(name,persist=true){tab=name;for(const n of ['causal','tree','process']){$('tab-'+n).setAttribute('aria-selected',String(n===name));$('tab-'+n).tabIndex=n===name?0:-1;$('panel-'+n).hidden=n!==name;}if(persist)save();}
function applyModel(next,source='Model',preferred=[]){const old={model,current,trace,search,result};const v=browserValidation(next);if(!v.ok){error(source+' was not applied. Previous result retained.\n'+v.errors.join('\n'));return false;}model=clone(next);if(!SCENARIOS.some(s=>JSON.stringify(s.model)===JSON.stringify(model))){current={id:'custom',title:model.title||'Your process',description:'An edited or imported model. All results use the explicit assumptions below.'};if(!$('scenario').querySelector('[value="custom"]'))$('scenario').insertAdjacentHTML('beforeend','<option value="custom">Your edited model</option>');}else current=SCENARIOS.find(s=>JSON.stringify(s.model)===JSON.stringify(model));updateControls();if(!run(preferred)){({model,current,trace,search,result}=old);updateControls();$('model-json').value=JSON.stringify(next,null,2);render();return false;}return true;}
$('scenario').onchange=()=>chooseScenario($('scenario').value);
$('generate').onclick=()=>run(trace);
$('execution').onchange=()=>selectTrace($('execution')._traces[Number($('execution').value)]);
$('allocation').onchange=()=>selectAllocation($('allocation').value);
$('show-added').onchange=()=>renderGraph();
$('capacity').oninput=()=>{$('capacity-output').value=$('capacity').value;};
$('capacity').onchange=()=>{const p=model.places.find(p=>p.kind==='resource');p.initial=Number($('capacity').value);$('model-json').value=JSON.stringify(model,null,2);run(trace);};
$('reset').onclick=()=>chooseScenario(current.id==='custom'?'refuge':current.id);
$('apply-model').onclick=()=>{try{applyModel(JSON.parse($('model-json').value));}catch(e){error('Model was not applied. Previous result retained.\n'+e.message);}};
$('export').onclick=()=>{const bundle={schema:'gimmer-causal-plan-result',version:VERSION,exportedAt:new Date().toISOString(),scenario:current.id,model,allocation,trace,search:{complete:search.complete,stats:search.stats,reason:search.reason},certificate:result};const blob=new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gimmer-causal-plan-'+current.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('save-status').textContent='Result export requested · includes model, trace, chosen ancestry and certificate.';};
$('import').onclick=()=>$('import-file').click();
$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>500000)throw Error('File exceeds the 500 kB model limit.');const data=JSON.parse(await file.text());if(data.schema==='gimmer-causal-plan-result'){if(data.version!==VERSION)throw Error('Unsupported result version.');const v=browserValidation(data.model);if(!v.ok)throw Error(v.errors.join('\n'));if(!['fifo','lifo'].includes(data.allocation)||!Array.isArray(data.trace))throw Error('Saved result is missing its ancestry or trace.');const check=analyse(data.model,data.trace,{allocation:data.allocation});if(!check.ok||!check.goalReached)throw Error('Saved trace cannot be certified: '+(check.errors?.join(' ')||'the goal is not reached.'));if(check.markings.slice(0,-1).some(m=>Object.entries(data.model.goal).every(([p,n])=>m[p]>=n)))throw Error('Saved trace continues after first reaching its goal.');const oldAllocation=allocation;allocation=data.allocation;if(!applyModel(data.model,'Saved result',data.trace)){allocation=oldAllocation;updateControls();return;}$('save-status').textContent='Opened and recomputed the saved result · imported certificate was not trusted.';}else applyModel(data,'Model');}catch(err){error('File was not opened. Previous result retained.\n'+err.message);}finally{e.target.value='';}};
document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{chooseScenario(b.dataset.case,true);setTab(b.dataset.case==='token-provenance'?'process':b.dataset.case==='n-obstruction'?'tree':'causal');});
document.querySelectorAll('[role=tab]').forEach(b=>{b.onclick=()=>setTab(b.id.slice(4));b.onkeydown=e=>{const names=['causal','tree','process'],i=names.indexOf(tab);if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setTab(names[j]);$('tab-'+names[j]).focus();}};});
setupOptions();
let restored=false;try{const data=JSON.parse(localStorage.getItem(KEY)||'null');if(data&&data.version===VERSION&&browserValidation(data.model).ok&&['fifo','lifo'].includes(data.allocation)){current=SCENARIOS.find(s=>s.id===data.scenario)||{id:'custom',title:data.model.title,description:'Your saved model.'};if(current.id==='custom')$('scenario').insertAdjacentHTML('beforeend','<option value="custom">Your edited model</option>');model=data.model;allocation=data.allocation;trace=Array.isArray(data.trace)?data.trace:[];tab=['causal','tree','process'].includes(data.tab)?data.tab:'causal';restored=true;}}catch{}
updateControls();if(!run(restored?trace:current.trace)){chooseScenario('refuge');error('The saved model could not be certified. The default example has been restored.');}
