import {SCENARIOS} from './scenarios.mjs';
import {validate,checkJointStart,compareModels} from './engine.mjs';
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>typeof n==='number'&&Number.isFinite(n)?(n!==0&&(Math.abs(n)<0.0001||Math.abs(n)>=1e12)?n.toExponential(6):n.toLocaleString(undefined,{maximumSignificantDigits:12})):'—';
const KEY='gimmer-marking-plan-model-v1',MAX_FILE_BYTES=2000000;
let model=null,result=null,worker=null,job=0,importGeneration=0,timer=null,scopeId='',planId='',stateId='',restoreUI=null;
let scenarioId=SCENARIOS[0]?.id,activeTab='plans';
const scenario=()=>SCENARIOS.find(s=>s.id===scenarioId)||SCENARIOS[0];
function status(message,kind=''){$('status').textContent=message;$('status').className='status '+kind;}
function stop(){job++;importGeneration++;if(worker){worker.terminate();worker=null;}clearTimeout(timer);$('cancel').hidden=true;$('generate').disabled=false;}
function invalidate(message){stop();result=null;$('results').hidden=true;status(message);}
function labels(){return Object.fromEntries((model?.transitions||[]).map(t=>[t.id,t.label||t.id]));}
function placeLabels(){return Object.fromEntries((model?.places||[]).map(p=>[p.id,p.label||p.id]));}
function describeCounts(counts){const names=placeLabels();return Object.entries(counts||{}).filter(([,n])=>n>0).map(([id,n])=>`${names[id]||id} × ${n}`).join(', ')||'None';}
function readModel(){let value;try{value=JSON.parse($('model-editor').value);}catch{throw Error('The model is not valid JSON. Correct the definition, or restore the example.');}const checked=validate(value);if(!checked.ok)throw Error((checked.errors||['Invalid model']).join(' '));return value;}
function renderInputs(){
 const s=SCENARIOS.find(s=>s.id===scenarioId);$('scenario').value=scenarioId||'custom';$('scenario-description').textContent=s?('Example context: '+s.description):'Custom model. Review its task signatures, initial marking and completion goal below.';
 $('scenario-notes').innerHTML=(s?.notes||[]).map(n=>`<p>${esc(n)}</p>`).join('');$('scenario-notes').hidden=!(s?.notes?.length);
 const resourceIds=(s?.resourcePlaces||[]).filter(id=>model.places.some(p=>p.id===id));
 const resources=resourceIds.length?model.places.filter(p=>resourceIds.includes(p.id)):model.places.filter(p=>p.kind==='resource');
 $('resource-controls').innerHTML=resources.map((p,i)=>`<label>${esc(p.label||p.id)}<input type="number" min="0" max="1000" step="1" data-place="${esc(p.id)}" id="resource-${i}" value="${p.initial}"></label>`).join('')||'<p class="muted">No resource places in this model. Initial conditions can be changed in the model definition.</p>';
 $('apply-resources').disabled=!resources.length;$('reset-example').disabled=!s;
 $('resource-controls').querySelectorAll('input').forEach(input=>input.oninput=()=>{try{const next=JSON.parse($('model-editor').value),n=Number(input.value);if(input.value.trim()===''||!Number.isSafeInteger(n)||n<0){invalidate('Resource counts must be nonnegative whole numbers. Correct the count before applying.');return;}const p=next.places.find(p=>p.id===input.dataset.place);if(p){p.initial=n;$('model-editor').value=JSON.stringify(next,null,2);}invalidate('Starting resource count edited. Generate plans to check the new marking.');}catch{invalidate('Correct the model definition before changing its resources.');}});
 const c=s?.comparison;$('apply-comparison').disabled=!c;
 $('comparison-description').textContent=c?(c.kind==='marking'?'Compare a different starting marking using the same process rules.':'Compare a changed mechanism rule. This is a different process assumption, not just another schedule.'):'Use the mechanism editor to explore a change; inspect the rule before generating.';
 $('model-editor').value=JSON.stringify(model,null,2);
 $('mechanism-table').querySelector('tbody').innerHTML=model.transitions.map(t=>`<tr><th scope="row">${esc(t.label||t.id)}</th><td>${esc(describeCounts(t.inputs))}</td><td>${esc(describeCounts(t.outputs))}</td><td>${fmt(t.duration)}</td></tr>`).join('');
 $('goal-description').textContent='Completion goal: '+describeCounts(model.goal)+'. Atomic trace search stops at first goal coverage; its timed schedule finishes every retained task. Each modelled task is available at most once.';
}
function loadModel(value,message,ui=null){model=clone(value);restoreUI=ui;renderInputs();$('change-note').textContent=message||'';run();}
function run(){
 stop();let candidate;try{candidate=readModel();}catch(e){invalidate(e.message);$('status').classList.add('error');return;}
 model=clone(candidate);renderInputs();result=null;$('results').hidden=true;$('generate').disabled=true;$('cancel').hidden=false;status('Generating reachable states, complete branches and their plan witnesses…');
 const id=++job;worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});
 worker.onmessage=({data})=>{if(data.id!==job)return;clearTimeout(timer);worker?.terminate();worker=null;$('generate').disabled=false;$('cancel').hidden=true;
  if(!data.result?.ok){result=null;status((data.result?.errors||['The calculation did not return a valid result.']).join(' '),'error');return;}
  result=data.result;renderResult();
 };
 worker.onerror=e=>{if(id!==job)return;stop();status('The calculation could not finish. '+(e.message||'Reload and try again.'),'error');};
 timer=setTimeout(()=>{if(id!==job)return;stop();result=null;status('Exploration stopped after 45 seconds. No complete result is claimed. Choose a smaller model or the small-sample budget, then generate again.','partial');},45000);
 const limits=$('budget').value==='small'?{maxStates:2,maxSteps:2,maxTraces:1,maxPlans:1,maxWitnesses:1}:{};
 worker.postMessage({id,model,limits});
}
function renderResult(){
 $('results').hidden=false;const plans=result.plans||[],states=result.states||[],scopes=result.scopes||[],traces=result.traces||[];
 $('completion').textContent=result.complete?'Complete within stated bounds':'Partial exploration';
 const goalCount=states.filter(s=>s.goalReached).length;
 status(result.complete?(plans.length?'Exploration complete within the declared bounds. Every retained plan has its own checked supply history.':'No first-goal plan exists within this declared once-only model.'):'Exploration reached a limit. Retained plans are examples; missing plans are not proved impossible.',result.complete?'':'partial');
 $('metrics').innerHTML=[[scopes.length,'work branches retained'],[plans.length,'plan witnesses retained'],[states.length,'reachable states retained'],[traces.length,'first-goal orders retained']].map(([n,l])=>`<div class="metric"><strong>${fmt(n)}</strong><span>${l}</span></div>`).join('');
 const c=result.completeness||{};
 $('bounds').innerHTML=`<strong>Completeness:</strong> ${Object.entries(c).map(([key,value])=>`${esc(key)} ${value===true?'complete':value===false?'partial':esc(JSON.stringify(value))}`).join(' · ')}.<br>Plans are earliest representatives for their supply histories, not all possible waiting-time choices. <details><summary>Effective limits and search evidence</summary><pre>${esc(JSON.stringify({limits:result.limits,stats:result.stats},null,2))}</pre></details>`;
 scopeId=restoreUI?.scopeId&&scopes.some(s=>s.id===restoreUI.scopeId)?restoreUI.scopeId:(scopes[0]?.id||'');
 planId=restoreUI?.planId||'';stateId=restoreUI?.stateId||states[0]?.id||'';
 renderScopes();renderPlanOptions();renderStateOptions();
 $('evidence-summary').innerHTML=`<h3>The retained evidence</h3><p>${fmt(states.length)} states and ${fmt((result.steps||[]).length)} jointly enabled starts were retained, including ${fmt(goalCount)} goal-covering states. The plan view retains ${fmt(traces.length)} serial first-goal executions and ${fmt(plans.length)} distinct supply-history witnesses across ${fmt(scopes.length)} work branches.</p><p>Each selected plan shows its own goal, inputs, outputs, resource handoffs and timed replay. Untouched tokens remain on identity wires. A successful representation check is specific to that witness and the stated token convention.</p><p>${result.complete?'The listed completeness checks all finished within their bounds.':'Some exploration or representation checks are incomplete; see the exact limits above.'}</p>`;
 setTab(restoreUI?.tab||activeTab);restoreUI=null;
}
function renderScopes(){const names=labels();$('scope-cards').innerHTML=(result.scopes||[]).map((s,i)=>`<button data-scope="${esc(s.id)}" class="${s.id===scopeId?'selected':''}" aria-pressed="${s.id===scopeId}"><strong>Work branch ${i+1}</strong><span>${esc(s.transitionIds.map(id=>names[id]||id).join(' · '))||'Already complete'}</span><small>${fmt(s.planIds?.length??0)} witnesses · ${s.complete&&s.minFinish!=null?`${fmt(s.minFinish)}–${fmt(s.maxFinish)} earliest finishes`:'timing range not certified complete'}</small></button>`).join('');$('scope-cards').querySelectorAll('button').forEach(b=>b.onclick=()=>{scopeId=b.dataset.scope;planId='';renderScopes();renderPlanOptions();});}
function renderPlanOptions(){const plans=(result.plans||[]).filter(p=>!scopeId||p.scopeId===scopeId);$('plan').innerHTML=plans.map((p,i)=>`<option value="${esc(p.id)}">Plan ${i+1} · finish ${fmt(p.makespan)} · ${p.exactTree?'exact work tree':'retain the dependency graph'}</option>`).join('');
 if(!plans.some(p=>p.id===planId))planId=plans[0]?.id||'';$('plan').value=planId;$('plan').disabled=!plans.length;$('selected-plan').hidden=!plans.length;$('plan-empty').hidden=!!plans.length;
 $('plan-empty').textContent=result.complete?'The goal cannot be completed under these modelled task and resource conditions. Inspect Project states for the remaining goal gaps.':'No plan was retained before the cutoff. This does not establish impossibility.';if(plans.length)renderPlan();}
function selectedPlan(){return (result?.plans||[]).find(p=>p.id===planId);}
function treeHTML(tree){if(!tree)return '';if(tree.type==='task')return `<li>${esc((labels()[tree.id?.replace(/#\d+$/,'')])||tree.label||tree.id)}</li>`;return `<li><span class="tree-kind">${tree.type==='parallel'?'May overlap':'In sequence'}</span><ul class="tree">${(tree.children||[]).map(treeHTML).join('')}</ul></li>`;}
function renderPlan(){const p=selectedPlan();if(!p)return;
 $('plan-summary').textContent=`This witness uses ${p.events.length} task occurrences and has earliest finish ${fmt(p.makespan)} in toy time units. It is supported by ${p.traceIds?.length??1} retained first-goal order(s).`;
 $('timeline').innerHTML=timelineSVG(p);
 $('work-tree').innerHTML=p.exactTree?`<p>This tree preserves this witness’s dependency order.</p><ul class="tree">${treeHTML(p.tree)}</ul>`:'<p><strong>Keep the dependency graph.</strong> One elementary sequence/parallel tree cannot express this witness exactly. Its lawful schedule and typed supplies remain available below.</p>';
 const replayOK=p.timedReplay?.ok===true,flags=p.monoidal?.verified,monoOK=flags===true||(flags?.tokenBalance===true&&flags?.framePreserved===true&&flags?.orderPreserved===true);
 $('plan-proof').innerHTML=`<ul><li>Goal coverage: ${p.goalReached?'reached':'not certified'}</li><li>Independent timed resource replay: ${replayOK?'passed':'see detailed result'}</li><li>Counted typed supplies and untouched context: ${monoOK?'verified':'see representation limits'}</li><li>Expanded composition term: ${flags?.compiled===true?'compiled and checked':p.monoidal?.term?'available; see detailed evidence':'not expanded; counted diagram retained'}</li><li>Timing is earliest for these chosen dependencies; no unrestricted optimisation claim.</li></ul><details><summary>Replay evidence</summary><pre>${esc(JSON.stringify(p.timedReplay,null,2))}</pre></details>`;
 $('wire-diagram').innerHTML=wireSVG(p);
 const wires=p.monoidal?.wires||[],eventNames=Object.fromEntries(p.events.map(e=>[e.id,e.label]));
 const endText=end=>end?.kind==='event'?(eventNames[end.eventId]||end.eventId):(end?.kind==='input'?'Initial boundary':'Final boundary');
 $('wire-table').innerHTML=`<table><caption>Every retained supply and its destination</caption><thead><tr><th>Supply type</th><th>Count</th><th>From</th><th>To</th></tr></thead><tbody>${wires.map(w=>`<tr><td>${esc(placeLabels()[w.place]||w.type||w.place)}<small>${esc(w.kind)}</small></td><td>${esc(w.count)}</td><td>${esc(endText(w.from))}</td><td>${esc(endText(w.to))}</td></tr>`).join('')}</tbody></table>`;
 $('monoidal-term').textContent=JSON.stringify({mode:p.monoidal?.mode,verified:p.monoidal?.verified,term:p.monoidal?.term,limits:p.monoidal?.reason||p.monoidal?.limits},null,2);
}
function timelineSVG(p){const width=940,left=235,right=65,row=46,height=80+p.events.length*row,max=p.makespan>0?p.makespan:1,span=width-left-right;const times=Object.fromEntries(p.schedule.map(s=>[s.id,s]));let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Earliest representative schedule. Each row is a task, with its start and finish labelled."><rect width="${width}" height="${height}" fill="#f7f5ef"/>`;
 for(let i=0;i<=5;i++){const value=max*(i/5),x=left+span*(i/5);svg+=`<line x1="${x}" x2="${x}" y1="28" y2="${height-20}" stroke="#d7ded5"/><text x="${x}" y="18" font-family="system-ui" font-size="11" fill="#52675d" text-anchor="middle">${fmt(value)}</text>`;}
 p.events.forEach((e,i)=>{const s=times[e.id],y=40+i*row;if(!s)return;const x=left+(s.start/max)*span,bar=Math.max(2,((s.end-s.start)/max)*span);svg+=`<text x="12" y="${y+19}" font-family="system-ui" font-size="12" fill="#17332f">${esc(e.label.length>31?e.label.slice(0,28)+'…':e.label)}</text><rect x="${x}" y="${y}" width="${bar}" height="27" rx="4" fill="#146c58"><title>${esc(e.label)}: ${fmt(s.start)} to ${fmt(s.end)}</title></rect><text x="${x+3}" y="${y+40}" font-family="system-ui" font-size="10" fill="#52675d">${fmt(s.start)} → ${fmt(s.end)}</text>`;});return svg+'</svg>';}
function wireSVG(p){const events=p.events,w=940,h=Math.max(160,70+events.length*76),pos=Object.fromEntries(events.map((e,i)=>[e.id,{x:170+(i%2)*415,y:45+i*76}]));let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Event dependencies in this typed supply witness. Full initial, final and identity wires appear in the table below."><defs><marker id="wire-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#52675d"/></marker></defs>`;
 for(const edge of p.edges||[]){const a=pos[edge.from],b=pos[edge.to];if(!a||!b)continue;const color=edge.kind==='resource'?'#a65e25':'#146c58';svg+=`<path d="M ${a.x+100} ${a.y+34} C ${a.x+100} ${a.y+60},${b.x+100} ${b.y-15},${b.x+100} ${b.y}" fill="none" stroke="${color}" stroke-width="2" marker-end="url(#wire-arrow)"><title>${esc(edge.place)} × ${esc(edge.count)}</title></path>`;}
 for(const e of events){const a=pos[e.id];svg+=`<rect x="${a.x}" y="${a.y}" width="225" height="34" rx="5" fill="#edf3ec" stroke="#146c58"/><text x="${a.x+10}" y="${a.y+22}" font-family="system-ui" font-size="12" fill="#17332f">${esc(e.label.length>28?e.label.slice(0,25)+'…':e.label)}</text>`;}
 if(!events.length)svg+='<text x="25" y="65" font-family="system-ui" fill="#17332f">Identity: the initial state already covers the goal.</text>';
 svg+=`<text x="15" y="${h-10}" font-family="system-ui" font-size="11" fill="#52675d">Green: condition supply · Ochre: allocated resource handoff · Full boundary and identity wires below</text></svg>`;return svg;}
function renderStateOptions(){const states=result.states||[];$('state').innerHTML=states.map((s,i)=>`<option value="${esc(s.id)}">State ${i+1}: ${s.fired.length?`${s.fired.length} tasks completed`:'initial marking'}${s.goalReached?' · goal covered':s.canReachGoal===false?' · cannot reach goal':''}</option>`).join('');if(!states.some(s=>s.id===stateId))stateId=states[0]?.id||'';$('state').value=stateId;renderState();}
function renderState(){const s=(result.states||[]).find(s=>s.id===stateId);if(!s)return;const names=labels(),places=placeLabels(),gaps=Array.isArray(s.goalGaps)?s.goalGaps.map(g=>`${places[g.place]||g.place}: short by ${g.shortfall}`).join(', '):describeCounts(s.goalGaps);$('state-summary').innerHTML=`<p><strong>${s.goalReached?'The goal is covered.':s.canReachGoal===true?'The goal is reachable from here.':s.canReachGoal===false?'No continuation reaches the goal in this declared model.':'Goal reachability remains unknown because exploration is incomplete.'}</strong></p><p>Completed: ${esc(s.fired.map(id=>names[id]||id).join(', ')||'none')}. Remaining goal conditions: ${esc(gaps||'none')}.</p>`;
 $('marking-table').innerHTML=`<table><caption>Available tokens at this decision point</caption><thead><tr><th>Place</th><th>Kind</th><th>Count</th></tr></thead><tbody>${model.places.map(p=>`<tr><th scope="row">${esc(p.label||p.id)}</th><td>${esc(p.kind)}</td><td>${esc(s.marking[p.id]||0)}</td></tr>`).join('')}</tbody></table>`;
 const remaining=model.transitions.filter(t=>!s.fired.includes(t.id));$('step-choices').innerHTML=remaining.map(t=>`<label><input type="checkbox" value="${esc(t.id)}">${esc(t.label||t.id)}${(s.enabled||[]).includes(t.id)?'':' (not individually enabled)'}</label>`).join('')||'<p>All modelled tasks have fired.</p>';
 const steps=(result.steps||[]).filter(step=>step.from===s.id);$('state-steps').innerHTML=steps.length?`<ul>${steps.map(step=>`<li>${esc(step.transitionIds.map(id=>names[id]||id).join(' + '))}</li>`).join('')}</ul>`:'<p>No nonempty start retained from this state.</p>';$('step-result').textContent='Select tasks and check their combined token demand.';
}
function checkStep(){const s=(result?.states||[]).find(s=>s.id===stateId);if(!s)return;const ids=[...$('step-choices').querySelectorAll('input:checked')].map(i=>i.value);try{const answer=checkJointStart(model,s.marking,s.fired,ids);$('step-result').innerHTML=`<strong>${answer.jointlyEnabled===true||answer.enabled===true?'These tasks can start together.':answer.ok===false?'The selection could not be checked.':'These tasks cannot start together.'}</strong><pre>${esc(JSON.stringify(answer,null,2))}</pre>`;}catch(e){$('step-result').textContent=e.message;}}
function setTab(name){if(!['plans','states','evidence'].includes(name))name='plans';activeTab=name;for(const tab of ['plans','states','evidence']){$('tab-'+tab).setAttribute('aria-selected',String(tab===name));$('tab-'+tab).tabIndex=tab===name?0:-1;$('panel-'+tab).hidden=tab!==name;}}
function snapshot(){return {format:'gimmer-marking-plan-model',version:1,savedAt:new Date().toISOString(),model:readModel(),scenarioId,ui:{scopeId,planId,stateId,tab:activeTab},budget:$('budget').value};}
function openSnapshot(value,origin){if(!value||value.format!=='gimmer-marking-plan-model'||value.version!==1||!value.model)throw Error('This is not a supported Gimmer marking-to-plan model file.');const checked=validate(value.model);if(!checked.ok)throw Error(checked.errors.join(' '));const exact=SCENARIOS.find(s=>JSON.stringify(s.model)===JSON.stringify(value.model));scenarioId=exact?.id||'';$('budget').value=value.budget==='small'?'small':'normal';loadModel(value.model,origin,value.ui);$('save-status').textContent=origin+' The model is being recomputed; saved result claims are not imported.';}
function save(){try{const value=snapshot();localStorage.setItem(KEY,JSON.stringify(value));const check=JSON.parse(localStorage.getItem(KEY));if(JSON.stringify(check)!==JSON.stringify(value))throw Error('The saved copy did not match.');$('save-status').textContent=`Saved “${value.model.title||value.model.id||'model'}” in this browser at ${new Date(value.savedAt).toLocaleString()}. Reopen saved model retrieves this copy. No remote file was changed.`;}catch(e){$('save-status').textContent='Not saved: '+e.message;}}
function reopen(){try{const raw=localStorage.getItem(KEY);if(!raw)throw Error('There is no saved model in this browser.');openSnapshot(JSON.parse(raw),'Opened the saved browser model.');}catch(e){$('save-status').textContent='Could not reopen: '+e.message;}}
function download(){try{const value=snapshot(),blob=new Blob([JSON.stringify(value)],{type:'application/json'});if(blob.size>MAX_FILE_BYTES)throw Error('Portable model exceeds the 2 MB limit.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gimmer-marking-plan-model.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('save-status').textContent='Portable model prepared for download. Open model file to recompute it here; this does not replace the saved browser copy.';}catch(e){$('save-status').textContent='Download not prepared: '+e.message;}}
async function importFile(){const file=$('import-file').files[0];if(!file)return;$('import-file').value='';stop();const token=importGeneration;$('cancel').hidden=false;status('Reading the model file. A newer selection or Cancel will supersede this import.');try{if(file.size>MAX_FILE_BYTES)throw Error('The file exceeds the 2 MB model limit.');const text=await file.text();if(token!==importGeneration)return;openSnapshot(JSON.parse(text),'Opened “'+file.name+'”.');}catch(e){if(token!==importGeneration)return;$('cancel').hidden=true;$('save-status').textContent='File not opened: '+e.message;status('File not opened. The current model is retained. '+e.message,'error');}}
$('scenario').innerHTML='<option value="custom" disabled>Custom model</option>'+SCENARIOS.map(s=>`<option value="${esc(s.id)}">${esc(s.title)}</option>`).join('');
$('scenario').onchange=()=>{scenarioId=$('scenario').value;scopeId='';planId='';stateId='';loadModel(scenario().model,'Loaded the supplied example. Its assumptions are visible in the mechanism review.');};
$('generate').onclick=run;$('cancel').onclick=()=>{stop();result=null;$('results').hidden=true;status('Cancelled. No result from this exploration is claimed. The model is retained for correction and retry.');};
$('budget').onchange=()=>invalidate('Exploration budget changed. Generate plans to use the new limit.');
$('model-editor').oninput=()=>{scenarioId='';$('scenario').value='custom';$('apply-comparison').disabled=true;$('reset-example').disabled=true;invalidate('Model edited. The previous result is hidden; generate again to check these assumptions.');};
$('apply-resources').onclick=()=>{try{const next=readModel();for(const input of $('resource-controls').querySelectorAll('input')){const n=Number(input.value);if(input.value.trim()===''||!Number.isSafeInteger(n)||n<0)throw Error('Resource counts must be nonnegative whole numbers.');next.places.find(p=>p.id===input.dataset.place).initial=n;}loadModel(next,'Changed the starting resource marking. Task inputs, outputs and durations are unchanged.');}catch(e){status(e.message,'error');}};
$('apply-comparison').onclick=()=>{const c=SCENARIOS.find(s=>s.id===scenarioId)?.comparison;if(c){try{const before=readModel(),difference=compareModels(before,c.model);loadModel(c.model,'Applied the supplied comparison model. Change relative to your previous definition: '+difference.category+'. Inspect the task signatures and marking for the exact assumptions.');}catch(e){status(e.message,'error');}}};
$('reset-example').onclick=()=>loadModel(scenario().model,'Restored the supplied example.');
$('plan').onchange=()=>{planId=$('plan').value;renderPlan();};$('state').onchange=()=>{stateId=$('state').value;renderState();};$('check-step').onclick=checkStep;
for(const name of ['plans','states','evidence']){$('tab-'+name).onclick=()=>setTab(name);$('tab-'+name).onkeydown=e=>{const tabs=['plans','states','evidence'],i=tabs.indexOf(name);let index;if(e.key==='ArrowRight')index=(i+1)%3;else if(e.key==='ArrowLeft')index=(i+2)%3;else if(e.key==='Home')index=0;else if(e.key==='End')index=2;else return;e.preventDefault();setTab(tabs[index]);$('tab-'+tabs[index]).focus();};}
$('save').onclick=save;$('reopen').onclick=reopen;$('download').onclick=download;$('import-file').onchange=importFile;$('forget').onclick=()=>{try{localStorage.removeItem(KEY);$('save-status').textContent='Removed this lab’s saved browser copy. The displayed model and downloaded files are unchanged.';}catch(e){$('save-status').textContent='Could not remove browser copy: '+e.message;}};
loadModel(scenario().model,'Supplied toy mechanism. Review its conditions and goal before using the result.');
