import {SCENARIOS as CAUSAL} from '../causal-plan-lab/scenarios.mjs';
import {FAMILY_SCENARIOS} from '../process-contract-lab/family-scenarios.mjs';
const clone=x=>JSON.parse(JSON.stringify(x));
const place=(id,label,initial=0,kind='condition')=>({id,label,initial,kind});
const task=(id,label,duration,inputs,outputs)=>({id,label,duration,inputs,outputs,maxFirings:1});
const refuge={id:'forward-refuge',title:'Refuge: two delivery methods, one completion goal',description:'A supplied finite toy mechanism. Survey releases delivery; one option token selects helicopter or winch. Foundation and panel work borrow lifting capacity; assembly and commissioning complete the refuge.',places:[place('surveyRequest','Site survey available',1),place('surveyed','Survey complete'),place('accessChoice','One delivery-method commitment',1),place('flightWindow','Helicopter flight window',1),place('crane','Reusable lifting token',1,'resource'),place('foundationReady','Foundation package available'),place('panelsReady','Panel package available'),place('foundationDone','Foundation package complete'),place('panelsDone','Panel package complete'),place('shellDone','Refuge assembled'),place('occupied','Refuge commissioned')],transitions:[task('survey','Survey access and site',1,{surveyRequest:1},{surveyed:1}),task('helicopter','Deliver by helicopter',2,{surveyed:1,accessChoice:1,flightWindow:1},{foundationReady:1,panelsReady:1}),task('winch','Deliver by winch',4,{surveyed:1,accessChoice:1},{foundationReady:1,panelsReady:1}),task('foundations','Prepare foundations',4,{foundationReady:1,crane:1},{foundationDone:1,crane:1}),task('panels','Prepare refuge panels',3,{panelsReady:1,crane:1},{panelsDone:1,crane:1}),task('assemble','Assemble the refuge',2,{foundationDone:1,panelsDone:1},{shellDone:1}),task('commission','Commission the refuge',1,{shellDone:1},{occupied:1})],goal:{occupied:1}};
const two=clone(refuge);two.places.find(p=>p.id==='crane').initial=2;
const rule=clone(two);rule.places.push(place('foundationRelease','Foundation release required by panel method'));rule.transitions.find(t=>t.id==='foundations').outputs.foundationRelease=1;rule.transitions.find(t=>t.id==='panels').inputs.foundationRelease=1;
const noLift=clone(refuge);noLift.places.find(p=>p.id==='crane').initial=0;
const noFlight=clone(refuge);noFlight.places.find(p=>p.id==='flightWindow').initial=0;
const invalid=clone(refuge);invalid.places.find(p=>p.id==='crane').initial=-1;
const notes=['All transitions are once-only toy assumptions; durations use arbitrary consistent time units.','Goal coverage is explicit and can leave unused tokens, including the winch branch\'s unused flight window.','A resource marking change is separate from changing a prerequisite rule.'];
export const SCENARIOS=[
 {id:'refuge-options',title:'Generate both ways to complete the refuge',description:refuge.description,model:refuge,resourcePlaces:['crane'],notes,comparison:{kind:'marking',model:clone(two)}},
 {id:'refuge-two-lifts',title:'Two lifting tokens change joint starts',description:'The same physical rules and completion goal with a changed resource marking. Serial orders alone cannot reveal the added joint-start freedom.',model:two,resourcePlaces:['crane'],notes,comparison:{kind:'mechanism',model:clone(rule)}},
 {id:'refuge-foundation-rule',title:'A changed rule retains ordering with spare capacity',description:'This supplied alternative mechanism requires the foundation release before panel preparation. The same two-token resource marking cannot remove that physical-rule constraint.',model:rule,resourcePlaces:['crane'],notes,comparison:{kind:'mechanism',model:clone(two)}},
 {id:'refuge-no-lift',title:'A valid marking that cannot finish',description:'Zero lifting capacity is a valid count marking. Delivery can finish, but no foundation or panel lift can start.',model:noLift,resourcePlaces:['crane'],notes},
 {id:'refuge-no-flight',title:'A missing flight window leaves the winch branch',description:'Changing only initial flight-window availability removes the helicopter option; the winch route still reaches the same goal.',model:noFlight,resourcePlaces:['crane'],notes},
 {id:'or-support',title:'Either completed support package can suffice',description:'Generate all first-goal traces and all compatible producer-count ancestries from the supplied alternative-support mechanism.',model:clone(FAMILY_SCENARIOS.find(s=>s.id==='or-support').model),resourcePlaces:[],notes:['An either/or prerequisite cannot be replaced by deleting both predecessor relations.']},
 {id:'selective-n',title:'Selective prerequisites survive as a typed graph',description:'The exact N dependency pattern has no elementary Seq/Par event-block tree, but its selective typed token wiring remains available.',model:clone(CAUSAL.find(s=>s.id==='n-obstruction').model),resourcePlaces:[],notes:['Failure of the restricted work-tree grammar is not failure of a symmetric monoidal token-flow representation.']},
 {id:'invalid-marking',title:'Reject a negative resource marking',description:'An intentionally malformed initial marking is rejected before any plan or concurrency claim is made.',model:invalid,resourcePlaces:['crane'],notes:['A negative token count is invalid, unlike the valid but uncompletable zero-capacity case.']}
];
