import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=(process.env.LAB_BASE_URL||'http://127.0.0.1:8788').replace(/\/$/,'');
const out=process.env.LAB_EVIDENCE_DIR||'/tmp/causal-plan-browser-evidence';
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:process.env.LAB_BROWSER_CHANNEL||undefined});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage(),errors=[],checks=[];
page.on('pageerror',e=>errors.push(String(e)));
async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
const text=id=>page.locator('#'+id).innerText();
async function scenario(id){await page.locator('#scenario').selectOption(id);await page.waitForFunction(()=>!document.querySelector('#generate').disabled);}
async function apply(model){await page.locator('#model-editor').evaluate(el=>el.open=true);await page.locator('#model-json').fill(JSON.stringify(model));await page.locator('#apply-model').click();}
try{
 await page.goto(base+'/apps/causal-plan-lab/');
 await page.waitForFunction(()=>document.querySelector('#search-status').textContent.includes('complete execution'));
 await check('default derives four complete refuge executions',async()=>{assert.equal(await page.locator('#execution option').count(),4);assert.match(await text('verdict'),/Exact tree found/);assert.match(await text('save-status'),/Saved in this browser/);});
 await check('generated alternative changes the selected access method',async()=>{const values=await page.locator('#execution option').allTextContents();const i=values.findIndex(t=>t.toLowerCase().includes('winch'));assert.ok(i>=0);await page.locator('#execution').selectOption(String(i));await page.locator('#tab-process').click();assert.match(await text('trace'),/winch/i);});
 await check('guided crossing retains DAG and refuses an exact tree',async()=>{await page.locator('[data-case="n-obstruction"]').click();assert.match(await text('verdict'),/no exact tree/);assert.equal(await page.locator('#obstruction').isVisible(),true);assert.match(await text('obstruction'),/A#1/);});
 await check('stage comparison displays both invented dependencies and lost freedom',async()=>{await page.locator('#stage-details summary').click();const t=await text('stage-difference');assert.match(t,/2 added precedence/);assert.match(t,/finish: 7/);assert.match(t,/finish: 11/);assert.match(t,/B#1 → D#1 → A#1 → C#1/);});
 await check('causal overlay and event inspector work',async()=>{await page.locator('#tab-causal').click();await page.locator('#show-added').check();assert.equal(await page.locator('#graph path[stroke-dasharray]').count(),2);await page.locator('#graph [data-event="C#1"]').click();assert.match(await text('edge-inspector'),/Receives:/);});
 await page.screenshot({path:path.join(out,'desktop-crossing.png'),fullPage:true});
 await check('provenance comparison holds markings and timing fixed',async()=>{await page.locator('[data-case="token-provenance"]').click();assert.match(await text('provenance-comparison'),/Collective marking trace: identical/);assert.match(await text('provenance-comparison'),/Earliest event timing: identical/);assert.match(await text('verdict'),/no exact tree/);});
 await check('ancestry flip produces the exact two-chain tree and six orders',async()=>{await page.locator('#flip-ancestry').click();assert.match(await text('verdict'),/Exact tree found/);await page.locator('#tab-tree').click();assert.match(await text('certificate'),/Lawful linear orders: 6\. Exact-tree orders: 6/);});
 await check('export gives a real inspectable file',async()=>{const pending=page.waitForEvent('download');await page.locator('#export').click();const download=await pending;await download.saveAs(path.join(out,'saved-result.json'));const d=JSON.parse(await fs.readFile(path.join(out,'saved-result.json'),'utf8'));assert.equal(d.schema,'gimmer-causal-plan-result');assert.equal(d.allocation,'lifo');assert.equal(d.certificate.exactTree,true);});
 await check('reload restores model ancestry selected trace and view',async()=>{await page.reload();await page.waitForFunction(()=>document.querySelector('#verdict').textContent==='Exact tree found');assert.equal(await page.locator('#allocation').inputValue(),'lifo');assert.equal(await page.locator('#scenario').inputValue(),'token-provenance');assert.equal(await page.locator('#tab-tree').getAttribute('aria-selected'),'true');assert.match(await text('certificate'),/Exact-tree orders: 6/);});
 await check('saved file reopens from another experiment and is recomputed',async()=>{await scenario('refuge');await page.locator('#import-file').setInputFiles(path.join(out,'saved-result.json'));await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('recomputed'));assert.equal(await page.locator('#allocation').inputValue(),'lifo');assert.equal(await page.locator('#scenario').inputValue(),'token-provenance');});
 await check('forged certificate is ignored on import',async()=>{const d=JSON.parse(await fs.readFile(path.join(out,'saved-result.json'),'utf8'));d.certificate={exactTree:false,makespan:999};await page.locator('#import-file').setInputFiles({name:'forged.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});assert.match(await text('verdict'),/Exact tree found/);assert.ok(!(await text('metrics')).includes('999'));});
 await check('illegal trace preserves previous result and explains rejection',async()=>{const d=JSON.parse(await fs.readFile(path.join(out,'saved-result.json'),'utf8'));d.trace=['B'];await page.locator('#import-file').setInputFiles({name:'illegal.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await page.waitForFunction(()=>!document.querySelector('#error').hidden);assert.match(await text('error'),/Previous result retained/);assert.match(await text('verdict'),/Exact tree found/);});
 await check('one versus two resource tokens changes valid earliest finish',async()=>{await scenario('shared-resource');assert.match(await text('metrics'),/7\s*earliest finish/);await page.locator('#capacity').fill('2');await page.locator('#capacity').dispatchEvent('change');assert.match(await text('metrics'),/4\s*earliest finish/);});
 await check('correction persists across reload',async()=>{await page.reload();await page.waitForFunction(()=>document.querySelector('#metrics').textContent.includes('earliest finish'));assert.equal(await page.locator('#capacity').inputValue(),'2');assert.match(await text('metrics'),/4\s*earliest finish/);});
 await check('invalid JSON retains prior valid result',async()=>{await page.locator('#model-editor').evaluate(el=>el.open=true);await page.locator('#model-json').fill('{broken');await page.locator('#apply-model').click();assert.match(await text('error'),/Previous result retained/);assert.match(await text('metrics'),/4\s*earliest finish/);});
 await check('numeric timing failure retains prior valid result',async()=>{const d=JSON.parse(await fs.readFile(path.join(out,'saved-result.json'),'utf8'));d.model.transitions.forEach(t=>t.duration=Number.MAX_VALUE);await apply(d.model);assert.match(await text('error'),/could not be certified/);assert.match(await text('metrics'),/4\s*earliest finish/);});
 await check('failed ancestry change retains matching controls and exported certificate',async()=>{await scenario('shared-resource');await page.locator('#capacity').fill('2');await page.locator('#capacity').dispatchEvent('change');const m=JSON.parse(await page.locator('#model-json').inputValue());m.transitions[0].duration=1e308;m.transitions[1].duration=1;await apply(m);assert.match(await text('verdict'),/Exact tree found/);await page.locator('#allocation').selectOption('lifo');assert.match(await text('error'),/could not be certified/);assert.equal(await page.locator('#allocation').inputValue(),'fifo');assert.ok(!(await text('search-status')).includes('Searching'));const pending=page.waitForEvent('download');await page.locator('#export').click();await (await pending).saveAs(path.join(out,'rollback-result.json'));const d=JSON.parse(await fs.readFile(path.join(out,'rollback-result.json'),'utf8'));assert.equal(d.allocation,'fifo');assert.equal(d.certificate.allocation,'fifo');assert.equal(d.certificate.ok,true);});
 await check('tiny positive timing is displayed without rounding to zero',async()=>{await scenario('refuge');const m=JSON.parse(await page.locator('#model-json').inputValue());m.transitions.forEach(t=>t.duration=0.00001);await apply(m);assert.match(await text('metrics'),/e-5/);});
 await check('valid places named marking tokens and counts show their real counts',async()=>{const m={id:'named-places',places:[{id:'marking',kind:'condition',initial:2},{id:'tokens',kind:'condition',initial:3},{id:'counts',kind:'condition',initial:4}],transitions:[],goal:{marking:1}};await apply(m);await page.locator('#tab-process').click();assert.deepEqual(await page.locator('#markings tbody tr td').allTextContents(),['Initial','2','3','4']);});
 await check('missing prerequisite is not certified as a plan',async()=>{await scenario('deadlock');assert.match(await text('verdict'),/No complete plan/);assert.match(await text('search-status'),/No complete execution reaches/);assert.equal(await page.locator('#export').isDisabled(),true);});
 await check('repeated firings keep separate occurrence identities',async()=>{await scenario('repeated-occurrence');assert.equal(await page.locator('#graph [data-event]').count(),2);assert.equal(await page.locator('#graph [data-event="prepare#2"]').count(),1);});
 const identity={id:'already-done',title:'Already complete',places:[{id:'done',kind:'condition',initial:1}],transitions:[],goal:{done:1}};
 await check('initial goal yields a real zero-event identity plan',async()=>{await apply(identity);assert.match(await text('verdict'),/Exact tree found/);assert.equal(await page.locator('#execution option').count(),1);assert.equal(await page.locator('#export').isDisabled(),false);await page.locator('#tab-process').click();assert.match(await text('trace'),/identity execution/);});
 await check('identity plan survives reload',async()=>{await page.reload();await page.waitForFunction(()=>document.querySelector('#verdict').textContent==='Exact tree found');assert.match(await text('trace'),/identity execution/);});
 await check('32-event computational cap states incomplete search',async()=>{const m={id:'long',title:'Long finite process',places:[{id:'raw',kind:'condition',initial:40},{id:'done',kind:'condition',initial:0}],transitions:[{id:'work',duration:1,maxFirings:40,inputs:{raw:1},outputs:{done:1}}],goal:{done:40}};await apply(m);assert.match(await text('search-status'),/does not establish impossibility/);assert.match(await text('verdict'),/No complete plan/);});
 await check('keyboard tab navigation uses arrows and restores focus',async()=>{await scenario('refuge');await page.locator('#tab-causal').click();await page.locator('#tab-causal').press('ArrowRight');assert.equal(await page.locator('#tab-tree').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#tab-tree').evaluate(e=>e===document.activeElement),true);});
 await check('mobile has no document-level horizontal overflow',async()=>{await page.setViewportSize({width:390,height:844});await scenario('n-obstruction');await page.locator('#tab-tree').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await page.screenshot({path:path.join(out,'mobile-tree.png'),fullPage:true});});
 await check('mobile controls remain usable',async()=>{await page.locator('[data-case="token-provenance"]').click();await page.locator('#flip-ancestry').click();assert.match(await text('verdict'),/Exact tree found/);});
 await check('entry and return routes reach the autonomous lab and external inherited baseline',async()=>{await page.goto(base+'/process-to-plan-lab/');assert.ok(await page.locator('a[href*="causal-plan-lab"]').count()>0);await page.locator('a[href*="causal-plan-lab"]').first().click();await page.waitForSelector('#generate');await page.locator('footer a').click();await page.locator('a[href*="mountain-refuge-petri-wbs-demo"]').first().click();await page.waitForLoadState('domcontentloaded');assert.ok((await page.title()).length>0);});
 await check('no uncaught browser exceptions',async()=>assert.deepEqual(errors,[]));
 await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify({base,checkedAt:new Date().toISOString(),agentOperated:true,humanValidation:false,checks:checks.length,names:checks,errors},null,2));
 console.log(JSON.stringify({checks:checks.length,errors,out}));
}finally{await browser.close();}
