name: Generate Multilayer Graph

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx matplotlib
      - name: Run script
        run: |
          python generate_multilayer_graph.py
      - name: Upload graph artifact
        uses: actions/upload-artifact@v4
        with:
          name: multilayer-graph
          path: multilayer_graph.png
